# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demopage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='demo',
        ),
        migrations.AddField(
            model_name='house',
            name='neighbourhood',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Demopage.Neighbourhood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demopage.House'),
        ),
    ]
