# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demopage', '0002_auto_20161121_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBalkjes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
