# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('used_power_battery', models.CharField(default=0, max_length=100)),
                ('available_power_battery', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Energy_Efficient_Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power', models.CharField(default=0, max_length=100)),
                ('duration', models.CharField(default=0, max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Energy_Non_Efficient_Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power', models.CharField(default=0, max_length=100)),
                ('duration', models.CharField(default=0, max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Energy_Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power', models.CharField(default=0, max_length=100)),
                ('duration', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Smart_Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power', models.CharField(default=0, max_length=100)),
                ('duration', models.CharField(default=0, max_length=100)),
                ('deadline', models.CharField(default=0, max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Total_Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_used_power', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed', models.CharField(default=0, max_length=100)),
                ('temperature', models.CharField(default=0, max_length=100)),
                ('light_intensity', models.CharField(default=0, max_length=100)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood')),
            ],
        ),
        migrations.RenameField(
            model_name='house',
            old_name='demo',
            new_name='neighbourhood',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('smart_devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neighbourhood.Smart_Devices')),
                ('temperature', models.CharField(default=0, max_length=100)),
            ],
            bases=('neighbourhood.smart_devices',),
        ),
        migrations.CreateModel(
            name='Dishwasher',
            fields=[
                ('smart_devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neighbourhood.Smart_Devices')),
                ('temperature', models.CharField(default=0, max_length=100)),
            ],
            bases=('neighbourhood.smart_devices',),
        ),
        migrations.CreateModel(
            name='Dryer',
            fields=[
                ('smart_devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neighbourhood.Smart_Devices')),
                ('temperature', models.CharField(default=0, max_length=100)),
            ],
            bases=('neighbourhood.smart_devices',),
        ),
        migrations.CreateModel(
            name='Electric_Car',
            fields=[
                ('smart_devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neighbourhood.Smart_Devices')),
                ('percentage_battery', models.CharField(default=0, max_length=100)),
                ('total_power', models.CharField(default=0, max_length=100)),
            ],
            bases=('neighbourhood.smart_devices',),
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('smart_devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neighbourhood.Smart_Devices')),
                ('temperature', models.CharField(default=0, max_length=100)),
            ],
            bases=('neighbourhood.smart_devices',),
        ),
        migrations.CreateModel(
            name='oven',
            fields=[
                ('energy_non_efficient_devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neighbourhood.Energy_Non_Efficient_Devices')),
                ('temperature', models.CharField(default=0, max_length=100)),
            ],
            bases=('neighbourhood.energy_non_efficient_devices',),
        ),
        migrations.CreateModel(
            name='Solar_BoIler',
            fields=[
                ('smart_devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neighbourhood.Smart_Devices')),
                ('temperature', models.CharField(default=0, max_length=100)),
            ],
            bases=('neighbourhood.smart_devices',),
        ),
        migrations.CreateModel(
            name='Solar_Pannels',
            fields=[
                ('energy_sources_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neighbourhood.Energy_Sources')),
                ('amount', models.CharField(default=0, max_length=100)),
            ],
            bases=('neighbourhood.energy_sources',),
        ),
        migrations.CreateModel(
            name='Washing_Machine',
            fields=[
                ('smart_devices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neighbourhood.Smart_Devices')),
                ('temperature', models.CharField(default=0, max_length=100)),
            ],
            bases=('neighbourhood.smart_devices',),
        ),
        migrations.CreateModel(
            name='wind_turbine',
            fields=[
                ('energy_sources_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neighbourhood.Energy_Sources')),
                ('speed_wind', models.CharField(default=0, max_length=100)),
            ],
            bases=('neighbourhood.energy_sources',),
        ),
        migrations.AddField(
            model_name='smart_devices',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Room'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Room'),
        ),
        migrations.AddField(
            model_name='energy_sources',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood'),
        ),
        migrations.AddField(
            model_name='energy_sources',
            name='room_energy_sources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Room'),
        ),
        migrations.AddField(
            model_name='energy_non_efficient_devices',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Room'),
        ),
        migrations.AddField(
            model_name='energy_efficient_devices',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Room'),
        ),
        migrations.AddField(
            model_name='battery',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Room'),
        ),
    ]
