# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0003_auto_20161205_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='ref_id',
            new_name='ip_adress',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='ref_id',
            new_name='ip_adress',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='ref_id',
            new_name='ip_adress',
        ),
    ]
