# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_auto_20161205_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default=0, max_length=100)),
                ('energy_price', models.CharField(default=0, max_length=100)),
                ('used_energy', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='optimal_status_fridges',
            name='name',
        ),
        migrations.RemoveField(
            model_name='optimal_status_heating',
            name='name',
        ),
        migrations.RemoveField(
            model_name='optimal_status_smart_devices',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plan_status_battery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plan_status_fridges',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plan_status_heating',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plan_status_stupid_devices',
            name='name',
        ),
        migrations.RenameField(
            model_name='battery',
            old_name='charged_status',
            new_name='begin_time',
        ),
        migrations.RenameField(
            model_name='battery',
            old_name='optimal_status',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='battery',
            old_name='planned_status',
            new_name='pin_number',
        ),
        migrations.RenameField(
            model_name='fridges',
            old_name='optimal_status',
            new_name='begin_time',
        ),
        migrations.RenameField(
            model_name='fridges',
            old_name='planned_status',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='heating',
            old_name='optimal_status',
            new_name='begin_time',
        ),
        migrations.RenameField(
            model_name='heating',
            old_name='planned_status',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='smart_devices',
            old_name='optimal_status',
            new_name='begin_time',
        ),
        migrations.RenameField(
            model_name='smart_devices',
            old_name='status_function',
            new_name='pin_number',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='room',
        ),
        migrations.RemoveField(
            model_name='smart_devices',
            name='house',
        ),
        migrations.AddField(
            model_name='battery',
            name='pin_type',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='fridges',
            name='pin_number',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='fridges',
            name='pin_type',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='heating',
            name='house',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.House'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heating',
            name='pin_number',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='heating',
            name='pin_type',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='smart_devices',
            name='pin_type',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='stupid_devices',
            name='pin_number',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='stupid_devices',
            name='pin_type',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='ip_address',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AlterField(
            model_name='smart_devices',
            name='status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.DeleteModel(
            name='Optimal_Status_Fridges',
        ),
        migrations.DeleteModel(
            name='Optimal_Status_Heating',
        ),
        migrations.DeleteModel(
            name='Optimal_Status_Smart_Devices',
        ),
        migrations.DeleteModel(
            name='Plan_Status_Battery',
        ),
        migrations.DeleteModel(
            name='Plan_Status_Fridges',
        ),
        migrations.DeleteModel(
            name='Plan_Status_Heating',
        ),
        migrations.DeleteModel(
            name='Plan_Status_Stupid_devices',
        ),
    ]
